### ISSUE TITLE
WPA2-PEAP Enterprise connection

### ISSUE THREAD

**Issue by gorghino** [chaeplin/esp8266_and_arduino#36]
Hi Chaeplin! This is more a request than an issue.
Could you try to test WPA2-PEAP connection with a esp8266? I'm trying with mine but I'm facing several problems with Arduino (https://github.com/esp8266/Arduino/issues/2595) and native OpenSDK (http://www.esp8266.com/viewtopic.php?f=159&t=12218).
Thank you!

**Comment by chaeplin** [comment]
I will try, it will take time. Currentely I am busy.
