### ISSUE TITLE
Just a question on ESP-01 firmware

### ISSUE THREAD

**Issue by mrohner** [chaeplin/esp8266_and_arduino#41]
I'm looking at the esp-01.ino in your node 49. Just wonder what firmware is running on the ESP-01.

**Comment by chaeplin** [comment]
_49-emontxv2-esp-01-i2c : both use Arduino.
esp-01 : https://github.com/esp8266/Arduino https://github.com/chaeplin/esp8266_and_arduino/blob/master/_49-emontxv2-esp-01-i2c/esp-01/esp-01.ino
emontxv2 : https://www.arduino.cc
https://github.com/chaeplin/esp8266_and_arduino/blob/master/_49-emontxv2-esp-01-i2c/emontxv2/emontxv2.ino
